spring.application.name=EchoAuthService

#spring.datasource.url=jdbc:mysql://34.100.220.92:3306/echoauthdb
spring.datasource.username=echoauthservice
spring.datasource.password=3ch0tech26!
#spring.datasource.url=jdbc:mysql://mysql-16029e00-echotech1820-737e.a.aivencloud.com:12743/defaultdb?sslMode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_olh9u0q79RkYjsnSB2e
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JDBC URL using the Google Socket Factory
# JDBC URL using the Google Socket Factory
spring.datasource.url=jdbc:mysql:///echoauthdb?cloudSqlInstance=echo-tech-507218:asia-south1:echoauthservice&socketFactory=com.google.cloud.sql.mysql.SocketFactory



spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=MyVeryLongSecretKeyForJwtAuthentication123456789012345
jwt.expiration=86400000
